# Educational/demo reference data. Not a prescribing database.
CONDITIONS = [
    {"name":"Common Cold","medicine_classes":["symptom-relief medicines"],"doctor_review":True},
    {"name":"Influenza (Flu)","medicine_classes":["antiviral medicines for selected patients"],"doctor_review":True},
    {"name":"Asthma","medicine_classes":["inhaled bronchodilators","inhaled corticosteroids"],"doctor_review":True},
    {"name":"Pneumonia","medicine_classes":["antibiotics when bacterial","cause-specific treatment"],"doctor_review":True},
    {"name":"Bronchitis","medicine_classes":["supportive treatment","cause-specific treatment"],"doctor_review":True},
    {"name":"Tuberculosis (TB)","medicine_classes":["combination anti-TB therapy"],"doctor_review":True},
    {"name":"COPD","medicine_classes":["bronchodilators","selected inhaled corticosteroids"],"doctor_review":True},
    {"name":"COVID-19","medicine_classes":["supportive treatment","antivirals for selected high-risk patients"],"doctor_review":True},
    {"name":"Hypertension","medicine_classes":["ACE inhibitors","ARBs","calcium-channel blockers","thiazide-type diuretics"],"doctor_review":True},
    {"name":"Coronary Artery Disease","medicine_classes":["antiplatelet","statin","anti-anginal and cardiovascular medicines"],"doctor_review":True},
    {"name":"Heart Failure","medicine_classes":["multiple guideline-directed cardiovascular medicine classes"],"doctor_review":True},
    {"name":"Anemia","medicine_classes":["iron","vitamin B12","folate depending on cause"],"doctor_review":True},
    {"name":"High Cholesterol","medicine_classes":["statins","other lipid-lowering medicines"],"doctor_review":True},
    {"name":"Type 1 Diabetes","medicine_classes":["insulin therapy"],"doctor_review":True},
    {"name":"Type 2 Diabetes","medicine_classes":["metformin","other glucose-lowering medicines"],"doctor_review":True},
    {"name":"Obesity","medicine_classes":["lifestyle treatment","selected anti-obesity medicines"],"doctor_review":True},
    {"name":"Thyroid Disorders","medicine_classes":["thyroid hormone replacement","antithyroid medicines depending on condition"],"doctor_review":True},
    {"name":"Dengue","medicine_classes":["supportive treatment"],"doctor_review":True},
    {"name":"Malaria","medicine_classes":["antimalarial regimen based on species and resistance"],"doctor_review":True},
    {"name":"Typhoid","medicine_classes":["appropriate antibiotic based on clinical assessment and resistance"],"doctor_review":True},
    {"name":"Cholera","medicine_classes":["oral/IV rehydration","antibiotics for selected patients"],"doctor_review":True},
    {"name":"Hepatitis","medicine_classes":["treatment varies by hepatitis type"],"doctor_review":True},
    {"name":"Urinary Tract Infection (UTI)","medicine_classes":["antibiotic selected according to assessment/testing"],"doctor_review":True},
    {"name":"Migraine","medicine_classes":["migraine-specific medicines","pain medicines"],"doctor_review":True},
    {"name":"Epilepsy","medicine_classes":["antiseizure medicines selected by seizure type"],"doctor_review":True},
    {"name":"Parkinson's Disease","medicine_classes":["dopaminergic and other neurologic medicines"],"doctor_review":True},
    {"name":"Stroke","medicine_classes":["emergency and cause-specific treatment"],"doctor_review":True},
    {"name":"Alzheimer's Disease","medicine_classes":["symptom-targeted medicines for selected patients"],"doctor_review":True},
    {"name":"Arthritis","medicine_classes":["analgesics","anti-inflammatory or disease-modifying medicines depending on type"],"doctor_review":True},
    {"name":"Osteoporosis","medicine_classes":["bone-strengthening medicines","calcium/vitamin D when appropriate"],"doctor_review":True},
    {"name":"Back Pain","medicine_classes":["pain-management options","physical therapy"],"doctor_review":True},
    {"name":"Gout","medicine_classes":["anti-inflammatory medicines","urate-lowering therapy"],"doctor_review":True},
    {"name":"Eczema","medicine_classes":["emollients","topical anti-inflammatory medicines"],"doctor_review":True},
    {"name":"Psoriasis","medicine_classes":["topical","systemic or biologic therapies depending on severity"],"doctor_review":True},
    {"name":"Acne","medicine_classes":["topical retinoids","benzoyl peroxide","other selected treatments"],"doctor_review":True},
    {"name":"Fungal Skin Infection","medicine_classes":["topical or systemic antifungals depending on site/severity"],"doctor_review":True},
    {"name":"Dermatitis","medicine_classes":["emollients","topical anti-inflammatory medicines"],"doctor_review":True},
    {"name":"Gastritis","medicine_classes":["acid-suppressing medicines","cause-specific treatment"],"doctor_review":True},
    {"name":"GERD / Acid Reflux","medicine_classes":["proton-pump inhibitors","H2 blockers"],"doctor_review":True},
    {"name":"Peptic Ulcer Disease","medicine_classes":["acid suppression","H. pylori eradication when confirmed"],"doctor_review":True},
    {"name":"Irritable Bowel Syndrome (IBS)","medicine_classes":["symptom-targeted medicines"],"doctor_review":True},
    {"name":"Gastroenteritis","medicine_classes":["rehydration","cause-specific treatment"],"doctor_review":True},
    {"name":"Conjunctivitis","medicine_classes":["treatment depends on infectious/allergic cause"],"doctor_review":True},
    {"name":"Cataract","medicine_classes":["surgical evaluation rather than routine tablets"],"doctor_review":True},
    {"name":"Glaucoma","medicine_classes":["pressure-lowering eye medicines"],"doctor_review":True},
    {"name":"Ear Infection","medicine_classes":["pain relief","antibiotic/other treatment depending on cause"],"doctor_review":True},
]

COMMON_MEDICINES = [
    {"area": "Fever / pain", "medicines": ["Paracetamol", "Ibuprofen"], "prescription": False},
    {"area": "Headache", "medicines": ["Paracetamol", "Ibuprofen"], "prescription": False},
    {"area": "Allergy", "medicines": ["Cetirizine", "Loratadine", "Fexofenadine"], "prescription": False},
    {"area": "Cold symptoms", "medicines": ["Cetirizine", "Loratadine", "Paracetamol"], "prescription": False},
    {"area": "Acidity / GERD", "medicines": ["Omeprazole", "Pantoprazole", "Famotidine"], "prescription": False},
    {"area": "Nausea", "medicines": ["Ondansetron", "Domperidone"], "prescription": True},
    {"area": "Constipation", "medicines": ["Psyllium", "Lactulose"], "prescription": False},
    {"area": "Diarrhea", "medicines": ["ORS", "Zinc preparations"], "prescription": False},
    {"area": "Muscle pain", "medicines": ["Diclofenac", "Ibuprofen"], "prescription": False},
    {"area": "Joint pain", "medicines": ["Paracetamol", "Diclofenac"], "prescription": False},
    {"area": "Skin allergy / itching", "medicines": ["Cetirizine", "Levocetirizine"], "prescription": False},
    {"area": "Fungal skin infection", "medicines": ["Clotrimazole", "Terbinafine"], "prescription": False},
    {"area": "Acne", "medicines": ["Benzoyl peroxide", "Adapalene"], "prescription": False},
    {"area": "High blood pressure", "medicines": ["Amlodipine", "Losartan", "Telmisartan"], "prescription": True},
    {"area": "Diabetes", "medicines": ["Metformin", "Glimepiride"], "prescription": True},
    {"area": "High cholesterol", "medicines": ["Atorvastatin", "Rosuvastatin"], "prescription": True},
    {"area": "Asthma", "medicines": ["Salbutamol inhaler", "Budesonide inhaler"], "prescription": True},
    {"area": "Thyroid", "medicines": ["Levothyroxine"], "prescription": True},
    {"area": "Iron deficiency", "medicines": ["Ferrous sulfate", "Ferrous fumarate"], "prescription": False},
    {"area": "Vitamin B12 deficiency", "medicines": ["Cyanocobalamin", "Methylcobalamin"], "prescription": False},
    {"area": "Vitamin D deficiency", "medicines": ["Cholecalciferol"], "prescription": False},
    {"area": "Migraine", "medicines": ["Sumatriptan"], "prescription": True},
    {"area": "Anxiety / depression", "medicines": ["Sertraline", "Escitalopram"], "prescription": True},
    {"area": "Bacterial infections", "medicines": ["Amoxicillin", "Azithromycin", "Doxycycline"], "prescription": True},
    {"area": "Urinary infection", "medicines": ["Antibiotic selection requires medical evaluation"], "prescription": True},
    {"area": "Heart conditions", "medicines": ["Aspirin", "Clopidogrel", "Atorvastatin"], "prescription": True},
]

RED_FLAGS = [
    "severe chest pain", "difficulty breathing", "shortness of breath",
    "unconscious", "fainted", "seizure", "stroke symptoms",
    "severe bleeding", "uncontrolled bleeding", "vomiting blood", "suicidal",
    "suicidal thoughts", "severe dehydration", "blue lips", "blue face",
    "sudden weakness", "one-sided weakness", "difficulty speaking",
    "sudden severe confusion", "sudden severe headache", "serious injury",
    "severe allergic reaction", "chest pressure", "coughing blood",
    "loss of consciousness", "విపరీతమైన శ్వాస ఇబ్బంది", "ఛాతీలో తీవ్రమైన నొప్పి",
    "స్పృహ కోల్పోవడం", "ఆత్మహత్య ఆలోచనలు", "सांस लेने में गंभीर कठिनाई",
    "सीने में तेज दर्द", "बेहोशी", "आत्महत्या के विचार"
]
